site_name: formal/orm
repo_name: formal/orm
docs_dir: documentation/

nav:
  - Home: index.md
  - Preface:
    - Philosophy: philosophy.md
    - Terminology: terminology.md
    - Limitations: limitations.md
  - Getting started:
    - getting-started/index.md
    - Create an aggregate: getting-started/aggregate.md
    - Persist an aggregate: getting-started/persist.md
    - Retrieve an aggregate: getting-started/retrieve.md
    - Update an aggregate: getting-started/update.md
    - Remove an aggregate: getting-started/remove.md
    - Count aggregates: getting-started/count.md
  - Mapping:
    - mapping/index.md
    - Custom type: mapping/type.md
    - Entities: mapping/entities.md
    - Optional entities: mapping/optionals.md
    - Collection of entities: mapping/collections.md
  - Specifications:
    - specifications/index.md
    - Create first specification: specifications/custom.md
    - Retrieve multiple aggregates: specifications/retrieve.md
    - Count multiple aggregates: specifications/count.md
    - Remove multiple aggregates: specifications/remove.md
  - Enums: enums.md
  - Pagination: pagination.md
  - Adapters:
    - adapters/index.md
    - Filesystem: adapters/filesystem.md
    - SQL: adapters/sql.md
    - Elasticsearch: adapters/elasticsearch.md
  - Benchmark: benchmark.md
  - Blog:
    - blog/index.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  font: false
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.action.edit
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: blue
      accent: deep orange
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: deep orange
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: blue
      accent: deep orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - abbr
  - admonition
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - privacy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/formal-php
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/Baptouuuu
