name: Extensive CI

on:
  push:
    tags:
      - '*'
    paths:
      - '.github/workflows/extensive.yml'

jobs:
  blackbox:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.4']
        dependency-versions: ['highest']
        mariadb: ['11']
        elasticsearch: ['7.17.18']
    name: 'BlackBox'
    services:
      mariadb:
        image: mariadb:${{ matrix.mariadb }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: example
        ports:
            - 3306
      elasticsearch:
        image: elasticsearch:${{ matrix.elasticsearch }}
        env:
          discovery.type: single-node
        ports:
          - 9200
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: example
        ports:
            - 5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: none
      - name: Composer
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: BlackBox
        run: php blackbox.php
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          POSTGRES_DB_PORT: ${{ job.services.postgres.ports[5432] }}
          ES_PORT: ${{ job.services.elasticsearch.ports[9200] }}
          CI: 'true'
          EXTENSIVE_CI: 'true'
